/* ---*--- Forms List ---*--- */
const FETCH_FORMS_LIST = 'FETCH_FORMS_LIST';


/* ---*--- Form ---*--- */
const TRY_UPDATE_CURRENT_FORM = 'TRY_UPDATE_CURRENT_FORM';
const SET_CURRENT_FORM_DATA = 'SET_CURRENT_FORM_DATA';
const SET_CURRENT_FORM_ENDPOINT = 'SET_CURRENT_FORM_ENDPOINT';

const SET_FORM_DATA_STATUS = 'SET_FORM_DATA_STATUS';

const FETCH_FORM = 'FETCH_FORM';
const FORM_FETCH_DONE = 'FORM_FETCH_DONE';

const SET_WIZARD_PAGES = 'SET_WIZARD_PAGES';
const JUMP_TO_WIZARD_PAGE = 'JUMP_TO_WIZARD_PAGE';


/* ---*--- Submission ---*--- */
const INITIALIZE_SUBMISSION = 'INITIALIZE_SUBMISSION';

const UPDATE_SUBMISSION_DATA_FOR_PAGE = 'UPDATE_SUBMISSION_DATA_FOR_PAGE';
const UPDATE_SUBMISSION_DATA_FOR_PAGE_LOCALLY = 'UPDATE_SUBMISSION_DATA_FOR_PAGE_LOCALLY';
const UPDATE_SUBMISSION_DATA_FOR_PAGE_ON_CLOUD = 'UPDATE_SUBMISSION_DATA_FOR_PAGE_ON_CLOUD';

const FETCH_SUBMISSION_DATA_FROM_CLOUD = 'FETCH_SUBMISSION_DATA_FROM_CLOUD';
const UPDATE_SUBMISSION_DATA_ALL_PAGES_LOCALLY = 'UPDATE_SUBMISSION_DATA_ALL_PAGES_LOCALLY';

const UPDATE_FIREBASE_SUBMISSION_ID = 'UPDATE_FIREBASE_SUBMISSION_ID';

const SUBMIT_TO_FORMIO_CURRENT = 'SUBMIT_TO_FORMIO_CURRENT';
const UPDATE_AND_SUBMIT_TO_FORMIO = 'UPDATE_AND_SUBMIT_TO_FORMIO';

const SUSPEND_FORM_INTERACTION_SESSION = 'SUSPEND_FORM_INTERACTION_SESSION';
const DIRECT_SUBMIT_DATA_FROM_CLOUD_TO_FORMIO = 'DIRECT_SUBMIT_DATA_FROM_CLOUD_TO_FORMIO';


export default {
  FETCH_FORMS_LIST,
  TRY_UPDATE_CURRENT_FORM,
  SET_CURRENT_FORM_DATA,
  SET_CURRENT_FORM_ENDPOINT,
  SET_FORM_DATA_STATUS,
  FETCH_FORM,
  FORM_FETCH_DONE,
  SET_WIZARD_PAGES,
  JUMP_TO_WIZARD_PAGE,
  INITIALIZE_SUBMISSION,
  UPDATE_SUBMISSION_DATA_FOR_PAGE,
  UPDATE_SUBMISSION_DATA_FOR_PAGE_LOCALLY,
  UPDATE_SUBMISSION_DATA_FOR_PAGE_ON_CLOUD,
  FETCH_SUBMISSION_DATA_FROM_CLOUD,
  UPDATE_SUBMISSION_DATA_ALL_PAGES_LOCALLY,
  UPDATE_FIREBASE_SUBMISSION_ID,
  SUBMIT_TO_FORMIO_CURRENT,
  UPDATE_AND_SUBMIT_TO_FORMIO,
  SUSPEND_FORM_INTERACTION_SESSION,
  DIRECT_SUBMIT_DATA_FROM_CLOUD_TO_FORMIO,
}
