const HEADER_TEXT_COLOR = '#000000';
const STANDARD_TEXT_COLOR = '#000000';
const ERROR_TEXT_COLOR = '#bd4b4b';
const SUCCESS_TEXT_COLOR = '#256329';
const DRAWER_HEADER_TEXT_COLOR = '#000000';
const FORM_GROUP_ITEM_TEXT_COLOR = '#000000';

const INPUT_BORDER_COLOR = '#000000';

const BASIC_CONTAINER_BACKGROUND_COLOR = '#FFFFFF';
const BASIC_IMAGE_CONTAINER_BACKGROUND_COLOR = '#FFFFFF';

const TAB_NAVIGATOR_BACKGROUND_COLOR = '#FFFFFF';
const TAB_NAVIGATOR_TINT_ACTIVE_COLOR = '#000000';
const TAB_NAVIGATOR_TINT_INACTIVE_COLOR = '#000000';
const TAB_NAVIGATOR_INDICATOR_COLOR = '#000000';

const TABLE_BORDER = '#000000';
const TABLE_CELL_BACKGROUND_STANDARD = '#000000';
const TABLE_CELL_BACKGROUND_HEAD = '#cccccc';

export default {
  HEADER_TEXT_COLOR,
  STANDARD_TEXT_COLOR,
  ERROR_TEXT_COLOR,
  SUCCESS_TEXT_COLOR,
  DRAWER_HEADER_TEXT_COLOR,
  FORM_GROUP_ITEM_TEXT_COLOR,
  INPUT_BORDER_COLOR,
  BASIC_CONTAINER_BACKGROUND_COLOR,
  BASIC_IMAGE_CONTAINER_BACKGROUND_COLOR,
  TAB_NAVIGATOR_BACKGROUND_COLOR,
  TAB_NAVIGATOR_TINT_ACTIVE_COLOR,
  TAB_NAVIGATOR_TINT_INACTIVE_COLOR,
  TAB_NAVIGATOR_INDICATOR_COLOR,
  TABLE_BORDER,
  TABLE_CELL_BACKGROUND_STANDARD,
  TABLE_CELL_BACKGROUND_HEAD,
};
